name: Build & Deploy

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    #define node version
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      # setting up node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # install
      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm ci

      # build
      - name: Build
        run: |
          npm run build:prod

      # karma test (single run - headless chrome)
      - name: Karma Test
        run: |
          npm run test:ci

      # deploy recent build and push it to branch 'gh-pages'
      # this will trigger the action 'pages build & deployment' to host the recent build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/angular-redux-shop
          publish_branch: gh-pages

      # wdio test
      #- name: Wdio Test
      #  run: |
      #    npm run e2e:wdio

      # playwright test
      #- name: Playwright Test
      #  run: |
      #    npm run e2e:playwright
